sudo: required
# Clean and don't fail
install:
  - sudo apt-get install hugo
  - rm -rf public || exit 0

# Build the website
script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  fqdn: $DEPLOY_DOMAIN
  on:
    branch: master